# Generated by Django 4.0.5 on 2022-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='')),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
            ],
        ),
    ]
